### ISSUE TITLE
[PE-D][Tester E] Image in user guide explaining inspect command is not accurate to the command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-2/tp#107]
![image.png](https://raw.githubusercontent.com/zicotjia/ped/main/files/11d04429-6c36-42b7-a6d6-3c90c720dfd0.png)

The image under the inspect command is the same as that under the help command. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: zicotjia/ped#1

**Comment by rui-han-crh** [comment]
Duplicate of #143 

Updated and fixed
