### ISSUE TITLE
[PE-D][Tester E] Error message is not accurate to the error

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-2/tp#116]
![image.png](https://raw.githubusercontent.com/zicotjia/ped/main/files/a4ae36e3-7ccc-44bc-848e-0c47648d5996.png)

Calling the Delete command improperly lead to the gui returning error message for the Find command

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: zicotjia/ped#3

**Comment by rui-han-crh** [comment]
Missing dedicated try catch in the usage of the `FindCommandParser` to rethrow an `EditCommand` related error
