### ISSUE TITLE
[PE-D][Tester B] [inspect] Invalid name inspect gives the wrong error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-2/tp#125]
Input: inspect unknownname

![invalid name inspect.png](https://raw.githubusercontent.com/jehousoh/ped/main/files/5095c8e6-cce6-4126-8318-fe9ff81fb0b9.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jehousoh/ped#7

**Comment by ryanczx** [comment]
Same as issue #128
