### ISSUE TITLE
[PE-D][Tester C] Inspecting Invalid Contact error message not correctly formatted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-2/tp#128]
![image.png](https://raw.githubusercontent.com/linuschui/ped/main/files/7a6115d8-eaa5-44aa-ad7a-6691f11836a3.png)

Inspecting invalid contact as shown above has displayed a %s formatter.  Perhaps your team could consider removing the "%s" or format the invalid contact name correctly into the formatter? :)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: linuschui/ped#3

**Comment by rui-han-crh** [comment]
Duplicate #139
