### ISSUE TITLE
[PE-D][Tester A] Example in UG for `addNote` is in the wrong format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-2/tp#147]
The format mentioned was: `addNote title/TITLE content/CONTENT [tag/TAG]...`

However the example given starts with `add`:

![image.png](https://raw.githubusercontent.com/Rachel-AG/ped/main/files/5df83d3a-4910-4e53-8f22-16c3ce79631f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Rachel-AG/ped#6

**Comment by rui-han-crh** [comment]
Fixed
