### ISSUE TITLE
[PE-D][Tester D] Error message missing whitespace

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-2/tp#149]
The parameters line seems to be missing some whitespace.

![image.png](https://raw.githubusercontent.com/notle1706/ped/main/files/15b8d443-ecd7-4778-a717-b70edf7f33bd.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: notle1706/ped#11

**Comment by rui-han-crh** [comment]
Duplicate #135
